### ISSUE TITLE
Plan para la dirección del proyecto

### ISSUE THREAD

**Issue by DavidAlejandroM** [calidadudea/Olimpo-#1]

**Comment by natienamorado** [comment]
![20-08-2019-Ges-Jerarquia-V1 1F](https://user-images.githubusercontent.com/25888026/65823476-8b90e000-e21c-11e9-90b0-a626356b6381.png)
![03092019-Ges-organigrama V0 1F](https://user-images.githubusercontent.com/25888026/65823473-83d13b80-e21c-11e9-900c-87cdc273a721.png)

**Comment by natienamorado** [comment]
esto quedo listo completamente
