### ISSUE TITLE
Identificar documentar los roles

### ISSUE THREAD

**Issue by DavidAlejandroM** [calidadudea/Olimpo-#23]

**Comment by natienamorado** [comment]
![03092019-Ges-OrdenjerarquicoV0 1](https://user-images.githubusercontent.com/25888026/64217721-1d0e6b80-ce84-11e9-9d5d-3bb70cedbc10.png)

**Comment by natienamorado** [comment]
![20-08-2019-Ges-Organigrama-V1 2F](https://user-images.githubusercontent.com/25888026/64217796-6959ab80-ce84-11e9-9e90-7a01fdfa3b4a.png)
Organigrama del proyecto
